### ISSUE TITLE
[Feature Request] Support saving file in a new directory

### ISSUE THREAD

**Issue by tsekityam** [githubocto/flat#59]
## What did I do
I setup a [repo](https://github.com/tsekityam/ark-funds-flat-data) to collect holdings of ARK funds using flat. The repo is up and running. 

However, the holding csv downloaded from https://ark-funds.com contains [a line of disclosure](https://github.com/tsekityam/ark-funds-flat-data/blob/c067ebf4144f856323ec98b097293d570d76207c/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv#L48) at the end of the files. I would like to remove the line by applying [a postprocessing script](https://github.com/tsekityam/ark-funds-flat-data/blob/c067ebf4144f856323ec98b097293d570d76207c/postprocess.js) to the raw file. 

I tried to save the files downloaded from https://ark-funds.com to `raw/ARK_INNOVATION_ETF_{fund}_HOLDINGS.csv`, and then use the script to remove the disclosure from the raw file, and save the cleared file in `ARK_INNOVATION_ETF_{fund}_HOLDINGS.csv`.

Here is the GitHub Action config I used:
```yaml
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv
          downloaded_filename: raw/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv
          axios_config: query.json
          postprocess: ./postprocess.js
```

## What did I see

GitHub Action execution [failed](https://github.com/tsekityam/ark-funds-flat-data/actions/runs/1328445127) because of `Error: ENOENT: no such file or directory, open 'raw/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv'`

## What do I want

The file can be created successfully. The action should help me to create the `raw` directory if it is not exist.
